default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: data-pipeline-7
      dataset: transfermarkt_core
      threads: 4
      keyfile: ../.keys/gcp_key.json
      timeout_seconds: 300
      priority: interactive
      retries: 1
