default:
  target: "{{ env_var('ENV_NAME') }}"
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('CORE_DATASET_NAME') }}"
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      timeout_seconds: 300
      priority: interactive
      retries: 1
    
    prod:
      type: bigquery
      method: service-account-json
      keyfile_json:
        type: "service_account"
        project_id: "{{ env_var('PROJECT_ID') }}"
        private_key_id: "{{ env_var('PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('PRIVATE_KEY') }}"
        client_email: "{{ env_var('CLIENT_EMAIL') }}"
        client_id: "{{ env_var('CLIENT_ID') }}"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/transfermarkt%40data-pipeline-7.iam.gserviceaccount.com"
      
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('CORE_DATASET_NAME') }}"
      threads: 6
      timeout_seconds: 300
      priority: interactive
      retries: 1
