default:
  target: "{{ env_var('DBT_PROFILES_TARGET') }}"
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('CORE_DATASET_NAME') }}"
      threads: 5
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      timeout_seconds: 300
      priority: interactive
      retries: 1
