version: 2

sources:
  - name: raw
    schema: transfermarkt_seed

    tables:
      - name: appearances
      - name: club_games
      - name: clubs
      - name: competitions
      - name: game_events
      - name: game_lineups
      - name: games
      - name: player_valuations
      - name: players
