version: 2

sources:
  - name: raw
    schema: "{{ env_var('SEED_DATASET_NAME') }}"
    tables:
      - name: appearances
      - name: club_games
      - name: clubs
      - name: game_events
      - name: game_lineups
      - name: games
      - name: player_valuations
      - name: players
