airflow:
    connections:
        - conn_id: ""
          conn_type: ""
          conn_host: ""
          conn_schema: ""
          conn_login: ""
          conn_password: ""
          conn_port: 0
          conn_uri: ""
          conn_extra:
            example_extra_field: example-value
        - conn_id: gcp
          conn_type: google_cloud_platform
          conn_host: ""
          conn_schema: ""
          conn_login: ""
          conn_password: ""
          conn_port: 0
          conn_uri: ""
          conn_extra:
            key_path: /usr/local/airflow/include/keys/gcp_key.json
            num_retries: "2"
    pools:
        - pool_name: ""
          pool_slot: 0
          pool_description: ""
        - pool_name: default_pool
          pool_slot: 128
          pool_description: Default pool
    variables:
        - variable_name: ""
          variable_value: ""
